---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aimterminal-env
  namespace: {{ .Release.Namespace }}
data:
  OPEN_TERMINAL_FILE_BROWSER_ROOT: {{ .Values.env.OPEN_TERMINAL_FILE_BROWSER_ROOT | quote }}
  OPEN_TERMINAL_PIP_PACKAGES: {{ .Values.env.OPEN_TERMINAL_PIP_PACKAGES | quote }}
  PIP_DISABLE_PIP_VERSION_CHECK: {{ .Values.env.PIP_DISABLE_PIP_VERSION_CHECK | quote }}
  PIP_NO_INPUT: {{ .Values.env.PIP_NO_INPUT | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aimterminal
  namespace: {{ .Release.Namespace }}
  labels:
    app: aimterminal
spec:
  replicas: {{ .Values.workloads.aimterminal.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: aimterminal
  strategy:
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      labels:
        app: aimterminal
    spec:
      enableServiceLinks: false
      containers:
      - name: aimterminal
        image: "{{ .Values.image.full }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: aimterminal-env
        env:
          - name: OPEN_TERMINAL_API_KEY
            valueFrom:
              secretKeyRef:
                name: aimterminal-secret
                key: OPEN_TERMINAL_API_KEY
        ports:
          - containerPort: {{ .Values.port }}
            name: http
        resources:
            {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          - name: home
            mountPath: /home/user
        startupProbe:
            {{- toYaml .Values.startupProbe | nindent 10 }}
        livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 10 }}
      volumes:
        - name: home
          hostPath:
            path: {{ .Values.userspace.appData }}/home
            type: DirectoryOrCreate
