---
apiVersion: v1
kind: Service
metadata:
  name: aimterminal
  namespace: {{ .Release.Namespace }}
  labels:
    app: aimterminal
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    app: aimterminal
